routes/web.php
<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::middleware(['auth', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('users', UserController::class);
    Route::post('/orders/confirm/{order}', [OrderController::class, 'confirm'])->name('user.orders.confirm');
    Route::post('/orders/reject/{order}', [OrderController::class, 'reject'])->name('user.orders.reject');
    Route::get('/orders', [OrderController::class, 'index'])->name('orders');
});

Route::middleware(['auth', 'user'])->prefix('user')->name('user.')->group(function () {
    Route::get('/dashboard', [App\Http\Controllers\User\DashboardController::class, 'index'])->name('dashboard');
    Route::resource('orders', App\Http\Controllers\User\OrderController::class)->only(['index', 'create', 'store']);
    Route::resource('order-history', App\Http\Controllers\User\OrderController::class)->only(['history']);
    Route::get('order-history', [App\Http\Controllers\User\OrderController::class, 'history'])->name('order-history');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Order extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'order_number',
        'type',
        'amount',
        'description',
        'receipt',
        'status',
    ];

    /**
     * Get the user that owns the order.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'current_balance',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function orders()
    {
        return $this->hasMany(Order::class, "user_id");
    }

    public function histories()
    {
        return $this->hasMany(Order::class, "user_id")->where('status','completed');
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    public function index()
    {
        $orders = Order::orderBy('id', 'desc')->get();
        return view('admin.orders.index', compact('orders'));
    }

    public function show(Order $order)
    {
        return view('admin.orders.show', compact('order'));
    }

    public function edit(Order $order)
    {
        return view('admin.orders.edit', compact('order'));
    }

    public function update(Request $request, Order $order)
    {
        $request->validate([
            'status' => 'required|string|in:pending,confirmed',
        ]);

        $order->update($request->all());

        return redirect()->route('admin.orders.index')->with('success', 'Order updated successfully.');
    }

    public function destroy(Order $order)
    {
        $order->delete();

        return redirect()->route('admin.orders.index')->with('success', 'Order deleted successfully.');
    }

    public function confirm(Order $order)
    {
        try {
            $user = User::find($order->user_id);
            $current_balance = $user->current_balance ?? 0;

            if($order->type == 'top-up'){
                $balance = $current_balance + $order->amount;
            } elseif ($order->type == 'transaction'){
                $balance = $current_balance - $order->amount;
            } else {
                $balance = $current_balance;
            }

            $order->status = 'completed';
            $order->save();

            $user->update([
                'current_balance' =>  $balance,
            ]);

            return response()->json(['success' => 'Order confirmed successfully.']);
        } catch (\Exception $e) {
            return response()->json(['error' => 'An error occurred while confirming the order.']);
        }
    }

    public function reject(Order $order)
    {
        $order->status = 'reject';
        $order->save();

        return response()->json(['success' => 'Order reject successfully.']);
    }


}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\Facades\DataTables;

class UserController extends Controller
{
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = User::all();
            return DataTables::of($data)
                ->addColumn('actions', function($row) {
                    $editUrl = route('admin.users.edit', $row->id);
                    $deleteUrl = route('admin.users.destroy', $row->id);
                    return '
                    <button data-id="' . $row->id . '" data-name="' . $row->name . '" data-email="' . $row->email . '" data-role="' . $row->role . '" class="btn btn-info viewBtn" data-toggle="modal" data-target="#viewUserModal">View</button>
                    <button data-id="' . $row->id . '" data-name="' . $row->name . '" data-email="' . $row->email . '" data-role="' . $row->role . '" class="btn btn-primary editBtn" data-toggle="modal" data-target="#editUserModal">Edit</button>
                    <button data-id="' . $row->id . '" class="btn btn-danger deleteBtn" data-toggle="modal" data-target="#deleteUserModal">Delete</button>
                ';
                })
                ->rawColumns(['actions'])
                ->make(true);
        }

        return view('admin.users.index');
    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
            'role' => 'required|string|in:admin,user',
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password),
            'role' => $request->role,
        ]);

        if ($request->ajax()) {
            return response()->json(['success' => 'User created successfully.', 'user' => $user]);
        }

        return redirect()->route('admin.users.index')->with('success', 'User created successfully.');
    }

    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    public function update(Request $request, User $user)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,' . $user->id,
            'role' => 'required|string|in:admin,user',
        ]);

        $user->update($validatedData);

        if ($request->ajax()) {
            return response()->json(['success' => 'User updated successfully.', 'user' => $user]);
        }

        return redirect()->route('admin.users.index')->with('success', 'User updated successfully.');
    }



    public function destroy(Request $request, User $user)
    {
        $user->delete();

        if ($request->ajax()) {
            return response()->json(['success' => 'User deleted successfully.']);
        }

        return redirect()->route('admin.users.index')->with('success', 'User deleted successfully.');
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index()
    {
        $user = auth()->user();

        $user->load(['orders']);

        $orders = $user->orders;

        $orderCount = $orders->count();

        $pendingCount = $orders->where('status', 'pending')->count();
        $completedCount = $orders->where('status', 'completed')->count();
        $rejectCount = $orders->where('status', 'reject')->count();

        $latestOrders = $orders->sortByDesc('created_at')->take(10);

        return view('user.dashboard', compact('latestOrders', 'orderCount', 'completedCount', 'pendingCount', 'rejectCount'));
    }


}

app/Http/Controllers/User/OrderController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Order;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OrderController extends Controller
{
    public function index()
    {
        $orders = auth()->user()->orders()->orderBy('id', 'desc')->get();
        return view('user.orders.index', compact('orders'));
    }

    public function create()
    {
        return view('user.orders.create');
    }

    public function store(Request $request)
    {
        $user = auth()->user();
        $request->validate([
            'type' => 'required|string|in:top-up,transaction',
            'amount' => [
                'required',
                'numeric',
                'regex:/^\d{1,12}(\.\d{1,2})?$/',
                function ($attribute, $value, $fail) use ($user, $request) {
                    if ($request->type === 'transaction' && $value > $user->current_balance) {
                        $fail('Balance Tidak Mencukupi, balance anda sekarang :'.'Rp ' . number_format($user->current_balance, 0, ',', '.'));
                    }
                },
            ],
            'description' => 'nullable|string',
            'receipt' => 'required_if:type,top-up|file|mimes:jpg,jpeg,png',
        ]);

        $order = new Order();
        $order->user_id = auth()->id();
        $order->order_number = $this->generateOrderNumber();
        $order->type = $request->type;
        $order->amount = $request->amount;
        $order->description = $request->description;
        if ($request->hasFile('receipt')) {
            $order->receipt = $request->file('receipt')->store('receipts', 'public');
        }
        $order->save();

        return redirect()->route('user.orders.index')->with('success', 'Order created successfully.');
    }

    private function generateOrderNumber()
    {
        $timestamp = now()->format('YmdHis');
        $randomNumber = str_pad(random_int(0, 9999), 4, '0', STR_PAD_LEFT);

        return 'ORD-' . $timestamp . '-' . $randomNumber;
    }

    public function history()
    {
        $user = auth()->user();
        $histories = $user->histories()->orderBy('id', 'desc')->paginate(10);

        $topup_total = $user->histories()->where('type', 'top-up')->sum('amount');
        $transaction_total = $user->histories()->where('type', 'transaction')->sum('amount');

        $current_balance = $user->current_balance;

        return view('user.orders.history', compact('histories', 'current_balance', 'topup_total', 'transaction_total'));
    }
}

resources/views/user/orders/create.blade.php
@extends('adminlte::page')

@section('title', 'Create Order')

@section('content_header')
    <h1>Create Order</h1>
@stop

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Order Form</h3>
        </div>
        <div class="card-body">
            <form id="order-form" action="{{ route('user.orders.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="type">Type</label>
                    <select name="type" id="type" class="form-control @error('type') is-invalid @enderror" required>
                        <option value="">Select Type</option>
                        <option value="top-up" {{ old('type') == 'top-up' ? 'selected' : '' }}>Top-Up</option>
                        <option value="transaction" {{ old('type') == 'transaction' ? 'selected' : '' }}>Transaction</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="amount">Amount</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Rp</span>
                        </div>
                        <input type="text" name="amount" id="amount" class="form-control @error('amount') is-invalid @enderror" value="{{ old('amount') }}" required>
                    </div>
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" id="description" class="form-control @error('description') is-invalid @enderror">{{ old('description') }}</textarea>
                </div>
                <div class="form-group" id="receipt-group" style="display: none;">
                    <label for="receipt">Receipt</label>
                    <input type="file" name="receipt" id="receipt" class="form-control @error('receipt') is-invalid @enderror">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

    <script>

        function formatNumber(value) {
            return value.replace(/\D/g, '').replace(/\B(?=(\d{3})+(?!\d))/g, ',');
        }

        function getNumber(value) {
            return value.replace(/,/g, '');
        }

        document.getElementById('type').addEventListener('change', function () {
            if (this.value === 'top-up') {
                document.getElementById('receipt-group').style.display = 'block';
            } else {
                document.getElementById('receipt-group').style.display = 'none';
            }
        });

        document.addEventListener('DOMContentLoaded', function () {
            if (document.getElementById('type').value === 'top-up') {
                document.getElementById('receipt-group').style.display = 'block';
            }

            const amountInput = document.getElementById('amount');
            amountInput.addEventListener('input', function () {
                const value = getNumber(this.value);
                this.value = formatNumber(value);
            });

            document.getElementById('order-form').addEventListener('submit', function () {
                const amountInput = document.getElementById('amount');
                amountInput.value = getNumber(amountInput.value);
            });
        });
    </script>
@stop

resources/views/user/orders/history.blade.php
@extends('adminlte::page')

@section('title', 'Balance History')

@section('plugins.Datatables', true)

@section('content_header')
    <h1>Balance History</h1>
@stop

@section('content')
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Balance</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3>Rp.{{ number_format($current_balance, 0, ',', '.') }}</h3>
                                <p>Current Balance</p>
                            </div>
                            <div class="icon mt-6 center">
                                <i class="fas fa-credit-card"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="small-box bg-primary">
                            <div class="inner">
                                <h3>Rp.{{ number_format($topup_total, 0, ',', '.') }}</h3>
                                <p>Total Top-Up</p>
                            </div>
                            <div class="icon mt-6 center">
                                <i class="fas fa-arrow-circle-down"></i>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>Rp.{{ number_format($transaction_total, 0, ',', '.') }}</h3>
                                <p>Total Transaction</p>
                            </div>
                            <div class="icon mt-6 center">
                                <i class="fas fa-arrow-circle-up"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <div class="row">
        <div class="col-md-3 mb-3">
            <label for="type_filter" class="form-label">Filter by Type:</label>
            <select id="type_filter" class="form-control select2">
                <option value="">All Types</option>
                <option value="top-up">Top-Up</option>
                <option value="transaction">Transaction</option>
            </select>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-body">
            <table id="orders-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Order Number</th>
                    <th class="text-center">Type</th>
                    <th class="text-center">Amount</th>
                    <th class="text-center">Balance</th>
                </tr>
                </thead>
                <tbody>
                @foreach($histories as $history)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $history->order_number }}</td>
                        <td class="text-center">
                            @if($history->type === 'top-up')
                                <span class="badge bg-primary">{{ ucfirst($history->type) }}</span>
                            @elseif($history->type === 'transaction')
                                <span class="badge bg-info">{{ ucfirst($history->type) }}</span>
                            @else
                                <span class="badge bg-secondary">{{ ucfirst($history->type) }}</span>
                            @endif
                        </td>
                        <td class="text-center"><b>{{ 'Rp ' . number_format($history->amount, 2, ',', '.') }}</b></td>
                        <td class="text-center">
                            @if($history->type === 'top-up')
                                <span class="text-success"><b>+ {{ 'Rp ' . number_format($history->amount, 2, ',', '.') }}</b></span>
                            @elseif($history->type === 'transaction')
                                <span class="text-danger"><b>- {{ 'Rp ' . number_format($history->amount, 2, ',', '.') }}</b></span>
                            @else
                                <b>{{ 'Rp ' . number_format($history->amount, 2, ',', '.') }}</b>
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('js')
    <script>
        $(document).ready(function() {
            var table = $('#orders-table').DataTable();

            $('#type_filter').on('change', function() {
                var type = $(this).val();
                table.columns(2).search(type).draw();
            });
        });
    </script>
@stop

resources/views/user/orders/index.blade.php
@extends('adminlte::page')

@section('title', 'My Orders')

@section('plugins.Datatables', true)

@section('content_header')
    <h1>My Orders</h1>
@stop

@section('content')
    <div class="col-md-2 pb-4">
        <a href="{{ route('user.orders.create') }}" class="btn btn-block btn-primary">Add Order</a>
    </div>
    <div class="row">
        <div class="col-md-3 mb-3">
            <label for="status_filter" class="form-label">Filter by Status:</label>
            <select id="status_filter" class="form-control select2">
                <option value="">All Statuses</option>
                <option value="pending">Pending</option>
                <option value="completed">Completed</option>
                <option value="reject">Rejected</option>
            </select>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-body">
            <table id="orders-table" class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Order Number</th>
                    <th>Type</th>
                    <th>Amount</th>
                    <th>Description</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">View Receipt</th>
                </tr>
                </thead>
                <tbody>
                @foreach($orders as $order)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>{{ $order->order_number }}</td>
                        <td>{{ ucfirst($order->type) }}</td>
                        <td>{{ 'Rp ' . number_format($order->amount, 2, ',', '.') }}</td>
                        <td>{{ $order->description }}</td>
                        <td class="text-center">
                            @if($order->status === 'pending')
                                <span class="badge bg-warning">{{ ucfirst($order->status) }}</span>
                            @elseif($order->status === 'completed')
                                <span class="badge bg-success">{{ ucfirst($order->status) }}</span>
                            @elseif($order->status === 'reject')
                                <span class="badge bg-danger">{{ ucfirst($order->status) }}</span>
                            @else
                                <span class="badge bg-secondary">{{ ucfirst($order->status) }}</span>
                            @endif
                        </td>
                        <td class="text-center">
                            @if($order->receipt)
                                <button class="btn btn-primary" data-toggle="modal" data-target="#receiptModal{{ $order->id }}">View Receipt</button>
                                <!-- Modal -->
                                <div class="modal fade" id="receiptModal{{ $order->id }}" tabindex="-1" role="dialog" aria-labelledby="receiptModalLabel{{ $order->id }}" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="receiptModalLabel{{ $order->id }}">Receipt</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <img src="{{ asset('storage/' . $order->receipt) }}" class="img-fluid" alt="Receipt">
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @else
                                -
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('js')
    <script>
        $(document).ready(function() {
            var table = $('#orders-table').DataTable();
            var orderId;

            $('#status_filter').on('change', function() {
                var status = $(this).val();
                table.columns(5).search(status).draw();
            });
        });
    </script>
@stop